JAVADIR=AudioRecorderApplet/src
TARGET=$(JAVADIR)/../AudioRecorderApplet.jar

all: 
	cd $(JAVADIR); make

clean:
	rm -f $(TARGET)
	rm -f $(JAVADIR)/AudioRecorderApplet.jar
	cd $(JAVADIR); make clean


